// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: media.proto

package com.jammed.app;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Media extends
      com.google.protobuf.GeneratedMessage {
    // Use Media.newBuilder() to construct.
    private Media() {
      initFields();
    }
    private Media(boolean noInit) {}
    
    private static final Media defaultInstance;
    public static Media getDefaultInstance() {
      return defaultInstance;
    }
    
    public Media getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jammed.app.Protos.internal_static_app_Media_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jammed.app.Protos.internal_static_app_Media_fieldAccessorTable;
    }
    
    // required .app.Message.Type type = 1 [default = MEDIA];
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private com.jammed.app.ProtocolMessage.Message.Type type_;
    public boolean hasType() { return hasType; }
    public com.jammed.app.ProtocolMessage.Message.Type getType() { return type_; }
    
    // required string location = 2;
    public static final int LOCATION_FIELD_NUMBER = 2;
    private boolean hasLocation;
    private java.lang.String location_ = "";
    public boolean hasLocation() { return hasLocation; }
    public java.lang.String getLocation() { return location_; }
    
    // required string title = 3;
    public static final int TITLE_FIELD_NUMBER = 3;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional int32 length = 4;
    public static final int LENGTH_FIELD_NUMBER = 4;
    private boolean hasLength;
    private int length_ = 0;
    public boolean hasLength() { return hasLength; }
    public int getLength() { return length_; }
    
    // optional string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string artist = 6;
    public static final int ARTIST_FIELD_NUMBER = 6;
    private boolean hasArtist;
    private java.lang.String artist_ = "";
    public boolean hasArtist() { return hasArtist; }
    public java.lang.String getArtist() { return artist_; }
    
    // optional string album = 7;
    public static final int ALBUM_FIELD_NUMBER = 7;
    private boolean hasAlbum;
    private java.lang.String album_ = "";
    public boolean hasAlbum() { return hasAlbum; }
    public java.lang.String getAlbum() { return album_; }
    
    private void initFields() {
      type_ = com.jammed.app.ProtocolMessage.Message.Type.MEDIA;
    }
    public final boolean isInitialized() {
      if (!hasType) return false;
      if (!hasLocation) return false;
      if (!hasTitle) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      if (hasLocation()) {
        output.writeString(2, getLocation());
      }
      if (hasTitle()) {
        output.writeString(3, getTitle());
      }
      if (hasLength()) {
        output.writeInt32(4, getLength());
      }
      if (hasName()) {
        output.writeString(5, getName());
      }
      if (hasArtist()) {
        output.writeString(6, getArtist());
      }
      if (hasAlbum()) {
        output.writeString(7, getAlbum());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      if (hasLocation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getLocation());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getTitle());
      }
      if (hasLength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getLength());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getName());
      }
      if (hasArtist()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getArtist());
      }
      if (hasAlbum()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getAlbum());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.jammed.app.Protos.Media parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jammed.app.Protos.Media parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Media parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jammed.app.Protos.Media parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Media parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jammed.app.Protos.Media parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Media parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jammed.app.Protos.Media parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jammed.app.Protos.Media parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jammed.app.Protos.Media parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jammed.app.Protos.Media prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.jammed.app.Protos.Media result;
      
      // Construct using com.jammed.app.Protos.Media.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.jammed.app.Protos.Media();
        return builder;
      }
      
      protected com.jammed.app.Protos.Media internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.jammed.app.Protos.Media();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jammed.app.Protos.Media.getDescriptor();
      }
      
      public com.jammed.app.Protos.Media getDefaultInstanceForType() {
        return com.jammed.app.Protos.Media.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.jammed.app.Protos.Media build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.jammed.app.Protos.Media buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.jammed.app.Protos.Media buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.jammed.app.Protos.Media returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jammed.app.Protos.Media) {
          return mergeFrom((com.jammed.app.Protos.Media)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.jammed.app.Protos.Media other) {
        if (other == com.jammed.app.Protos.Media.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLocation()) {
          setLocation(other.getLocation());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasArtist()) {
          setArtist(other.getArtist());
        }
        if (other.hasAlbum()) {
          setAlbum(other.getAlbum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.jammed.app.ProtocolMessage.Message.Type value = com.jammed.app.ProtocolMessage.Message.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 18: {
              setLocation(input.readString());
              break;
            }
            case 26: {
              setTitle(input.readString());
              break;
            }
            case 32: {
              setLength(input.readInt32());
              break;
            }
            case 42: {
              setName(input.readString());
              break;
            }
            case 50: {
              setArtist(input.readString());
              break;
            }
            case 58: {
              setAlbum(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .app.Message.Type type = 1 [default = MEDIA];
      public boolean hasType() {
        return result.hasType();
      }
      public com.jammed.app.ProtocolMessage.Message.Type getType() {
        return result.getType();
      }
      public Builder setType(com.jammed.app.ProtocolMessage.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.jammed.app.ProtocolMessage.Message.Type.MEDIA;
        return this;
      }
      
      // required string location = 2;
      public boolean hasLocation() {
        return result.hasLocation();
      }
      public java.lang.String getLocation() {
        return result.getLocation();
      }
      public Builder setLocation(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLocation = true;
        result.location_ = value;
        return this;
      }
      public Builder clearLocation() {
        result.hasLocation = false;
        result.location_ = getDefaultInstance().getLocation();
        return this;
      }
      
      // required string title = 3;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // optional int32 length = 4;
      public boolean hasLength() {
        return result.hasLength();
      }
      public int getLength() {
        return result.getLength();
      }
      public Builder setLength(int value) {
        result.hasLength = true;
        result.length_ = value;
        return this;
      }
      public Builder clearLength() {
        result.hasLength = false;
        result.length_ = 0;
        return this;
      }
      
      // optional string name = 5;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string artist = 6;
      public boolean hasArtist() {
        return result.hasArtist();
      }
      public java.lang.String getArtist() {
        return result.getArtist();
      }
      public Builder setArtist(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasArtist = true;
        result.artist_ = value;
        return this;
      }
      public Builder clearArtist() {
        result.hasArtist = false;
        result.artist_ = getDefaultInstance().getArtist();
        return this;
      }
      
      // optional string album = 7;
      public boolean hasAlbum() {
        return result.hasAlbum();
      }
      public java.lang.String getAlbum() {
        return result.getAlbum();
      }
      public Builder setAlbum(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAlbum = true;
        result.album_ = value;
        return this;
      }
      public Builder clearAlbum() {
        result.hasAlbum = false;
        result.album_ = getDefaultInstance().getAlbum();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:app.Media)
    }
    
    static {
      defaultInstance = new Media(true);
      com.jammed.app.Protos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:app.Media)
  }
  
  public static final class Playlist extends
      com.google.protobuf.GeneratedMessage {
    // Use Playlist.newBuilder() to construct.
    private Playlist() {
      initFields();
    }
    private Playlist(boolean noInit) {}
    
    private static final Playlist defaultInstance;
    public static Playlist getDefaultInstance() {
      return defaultInstance;
    }
    
    public Playlist getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jammed.app.Protos.internal_static_app_Playlist_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jammed.app.Protos.internal_static_app_Playlist_fieldAccessorTable;
    }
    
    // required .app.Message.Type type = 1 [default = PLAYLIST];
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private com.jammed.app.ProtocolMessage.Message.Type type_;
    public boolean hasType() { return hasType; }
    public com.jammed.app.ProtocolMessage.Message.Type getType() { return type_; }
    
    // repeated .app.Media media = 2;
    public static final int MEDIA_FIELD_NUMBER = 2;
    private java.util.List<com.jammed.app.Protos.Media> media_ =
      java.util.Collections.emptyList();
    public java.util.List<com.jammed.app.Protos.Media> getMediaList() {
      return media_;
    }
    public int getMediaCount() { return media_.size(); }
    public com.jammed.app.Protos.Media getMedia(int index) {
      return media_.get(index);
    }
    
    // required string host = 3;
    public static final int HOST_FIELD_NUMBER = 3;
    private boolean hasHost;
    private java.lang.String host_ = "";
    public boolean hasHost() { return hasHost; }
    public java.lang.String getHost() { return host_; }
    
    // optional int32 request = 4;
    public static final int REQUEST_FIELD_NUMBER = 4;
    private boolean hasRequest;
    private int request_ = 0;
    public boolean hasRequest() { return hasRequest; }
    public int getRequest() { return request_; }
    
    private void initFields() {
      type_ = com.jammed.app.ProtocolMessage.Message.Type.PLAYLIST;
    }
    public final boolean isInitialized() {
      if (!hasType) return false;
      if (!hasHost) return false;
      for (com.jammed.app.Protos.Media element : getMediaList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      for (com.jammed.app.Protos.Media element : getMediaList()) {
        output.writeMessage(2, element);
      }
      if (hasHost()) {
        output.writeString(3, getHost());
      }
      if (hasRequest()) {
        output.writeInt32(4, getRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      for (com.jammed.app.Protos.Media element : getMediaList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      if (hasHost()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getHost());
      }
      if (hasRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.jammed.app.Protos.Playlist parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jammed.app.Protos.Playlist parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Playlist parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jammed.app.Protos.Playlist parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Playlist parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jammed.app.Protos.Playlist parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Playlist parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jammed.app.Protos.Playlist parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jammed.app.Protos.Playlist parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jammed.app.Protos.Playlist parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jammed.app.Protos.Playlist prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.jammed.app.Protos.Playlist result;
      
      // Construct using com.jammed.app.Protos.Playlist.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.jammed.app.Protos.Playlist();
        return builder;
      }
      
      protected com.jammed.app.Protos.Playlist internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.jammed.app.Protos.Playlist();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jammed.app.Protos.Playlist.getDescriptor();
      }
      
      public com.jammed.app.Protos.Playlist getDefaultInstanceForType() {
        return com.jammed.app.Protos.Playlist.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.jammed.app.Protos.Playlist build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.jammed.app.Protos.Playlist buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.jammed.app.Protos.Playlist buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.media_ != java.util.Collections.EMPTY_LIST) {
          result.media_ =
            java.util.Collections.unmodifiableList(result.media_);
        }
        com.jammed.app.Protos.Playlist returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jammed.app.Protos.Playlist) {
          return mergeFrom((com.jammed.app.Protos.Playlist)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.jammed.app.Protos.Playlist other) {
        if (other == com.jammed.app.Protos.Playlist.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.media_.isEmpty()) {
          if (result.media_.isEmpty()) {
            result.media_ = new java.util.ArrayList<com.jammed.app.Protos.Media>();
          }
          result.media_.addAll(other.media_);
        }
        if (other.hasHost()) {
          setHost(other.getHost());
        }
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.jammed.app.ProtocolMessage.Message.Type value = com.jammed.app.ProtocolMessage.Message.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 18: {
              com.jammed.app.Protos.Media.Builder subBuilder = com.jammed.app.Protos.Media.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMedia(subBuilder.buildPartial());
              break;
            }
            case 26: {
              setHost(input.readString());
              break;
            }
            case 32: {
              setRequest(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required .app.Message.Type type = 1 [default = PLAYLIST];
      public boolean hasType() {
        return result.hasType();
      }
      public com.jammed.app.ProtocolMessage.Message.Type getType() {
        return result.getType();
      }
      public Builder setType(com.jammed.app.ProtocolMessage.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.jammed.app.ProtocolMessage.Message.Type.PLAYLIST;
        return this;
      }
      
      // repeated .app.Media media = 2;
      public java.util.List<com.jammed.app.Protos.Media> getMediaList() {
        return java.util.Collections.unmodifiableList(result.media_);
      }
      public int getMediaCount() {
        return result.getMediaCount();
      }
      public com.jammed.app.Protos.Media getMedia(int index) {
        return result.getMedia(index);
      }
      public Builder setMedia(int index, com.jammed.app.Protos.Media value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.media_.set(index, value);
        return this;
      }
      public Builder setMedia(int index, com.jammed.app.Protos.Media.Builder builderForValue) {
        result.media_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMedia(com.jammed.app.Protos.Media value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.media_.isEmpty()) {
          result.media_ = new java.util.ArrayList<com.jammed.app.Protos.Media>();
        }
        result.media_.add(value);
        return this;
      }
      public Builder addMedia(com.jammed.app.Protos.Media.Builder builderForValue) {
        if (result.media_.isEmpty()) {
          result.media_ = new java.util.ArrayList<com.jammed.app.Protos.Media>();
        }
        result.media_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMedia(
          java.lang.Iterable<? extends com.jammed.app.Protos.Media> values) {
        if (result.media_.isEmpty()) {
          result.media_ = new java.util.ArrayList<com.jammed.app.Protos.Media>();
        }
        super.addAll(values, result.media_);
        return this;
      }
      public Builder clearMedia() {
        result.media_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string host = 3;
      public boolean hasHost() {
        return result.hasHost();
      }
      public java.lang.String getHost() {
        return result.getHost();
      }
      public Builder setHost(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHost = true;
        result.host_ = value;
        return this;
      }
      public Builder clearHost() {
        result.hasHost = false;
        result.host_ = getDefaultInstance().getHost();
        return this;
      }
      
      // optional int32 request = 4;
      public boolean hasRequest() {
        return result.hasRequest();
      }
      public int getRequest() {
        return result.getRequest();
      }
      public Builder setRequest(int value) {
        result.hasRequest = true;
        result.request_ = value;
        return this;
      }
      public Builder clearRequest() {
        result.hasRequest = false;
        result.request_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:app.Playlist)
    }
    
    static {
      defaultInstance = new Playlist(true);
      com.jammed.app.Protos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:app.Playlist)
  }
  
  public static final class Library extends
      com.google.protobuf.GeneratedMessage {
    // Use Library.newBuilder() to construct.
    private Library() {
      initFields();
    }
    private Library(boolean noInit) {}
    
    private static final Library defaultInstance;
    public static Library getDefaultInstance() {
      return defaultInstance;
    }
    
    public Library getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jammed.app.Protos.internal_static_app_Library_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jammed.app.Protos.internal_static_app_Library_fieldAccessorTable;
    }
    
    // required .app.Message.Type type = 1 [default = LIBRARY];
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private com.jammed.app.ProtocolMessage.Message.Type type_;
    public boolean hasType() { return hasType; }
    public com.jammed.app.ProtocolMessage.Message.Type getType() { return type_; }
    
    // repeated .app.Playlist local = 2;
    public static final int LOCAL_FIELD_NUMBER = 2;
    private java.util.List<com.jammed.app.Protos.Playlist> local_ =
      java.util.Collections.emptyList();
    public java.util.List<com.jammed.app.Protos.Playlist> getLocalList() {
      return local_;
    }
    public int getLocalCount() { return local_.size(); }
    public com.jammed.app.Protos.Playlist getLocal(int index) {
      return local_.get(index);
    }
    
    // repeated .app.Playlist remote = 3;
    public static final int REMOTE_FIELD_NUMBER = 3;
    private java.util.List<com.jammed.app.Protos.Playlist> remote_ =
      java.util.Collections.emptyList();
    public java.util.List<com.jammed.app.Protos.Playlist> getRemoteList() {
      return remote_;
    }
    public int getRemoteCount() { return remote_.size(); }
    public com.jammed.app.Protos.Playlist getRemote(int index) {
      return remote_.get(index);
    }
    
    private void initFields() {
      type_ = com.jammed.app.ProtocolMessage.Message.Type.LIBRARY;
    }
    public final boolean isInitialized() {
      if (!hasType) return false;
      for (com.jammed.app.Protos.Playlist element : getLocalList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.jammed.app.Protos.Playlist element : getRemoteList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      for (com.jammed.app.Protos.Playlist element : getLocalList()) {
        output.writeMessage(2, element);
      }
      for (com.jammed.app.Protos.Playlist element : getRemoteList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      for (com.jammed.app.Protos.Playlist element : getLocalList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      for (com.jammed.app.Protos.Playlist element : getRemoteList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.jammed.app.Protos.Library parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jammed.app.Protos.Library parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Library parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jammed.app.Protos.Library parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Library parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jammed.app.Protos.Library parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Library parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jammed.app.Protos.Library parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jammed.app.Protos.Library parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jammed.app.Protos.Library parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jammed.app.Protos.Library prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.jammed.app.Protos.Library result;
      
      // Construct using com.jammed.app.Protos.Library.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.jammed.app.Protos.Library();
        return builder;
      }
      
      protected com.jammed.app.Protos.Library internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.jammed.app.Protos.Library();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jammed.app.Protos.Library.getDescriptor();
      }
      
      public com.jammed.app.Protos.Library getDefaultInstanceForType() {
        return com.jammed.app.Protos.Library.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.jammed.app.Protos.Library build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.jammed.app.Protos.Library buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.jammed.app.Protos.Library buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.local_ != java.util.Collections.EMPTY_LIST) {
          result.local_ =
            java.util.Collections.unmodifiableList(result.local_);
        }
        if (result.remote_ != java.util.Collections.EMPTY_LIST) {
          result.remote_ =
            java.util.Collections.unmodifiableList(result.remote_);
        }
        com.jammed.app.Protos.Library returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jammed.app.Protos.Library) {
          return mergeFrom((com.jammed.app.Protos.Library)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.jammed.app.Protos.Library other) {
        if (other == com.jammed.app.Protos.Library.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.local_.isEmpty()) {
          if (result.local_.isEmpty()) {
            result.local_ = new java.util.ArrayList<com.jammed.app.Protos.Playlist>();
          }
          result.local_.addAll(other.local_);
        }
        if (!other.remote_.isEmpty()) {
          if (result.remote_.isEmpty()) {
            result.remote_ = new java.util.ArrayList<com.jammed.app.Protos.Playlist>();
          }
          result.remote_.addAll(other.remote_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.jammed.app.ProtocolMessage.Message.Type value = com.jammed.app.ProtocolMessage.Message.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 18: {
              com.jammed.app.Protos.Playlist.Builder subBuilder = com.jammed.app.Protos.Playlist.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLocal(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.jammed.app.Protos.Playlist.Builder subBuilder = com.jammed.app.Protos.Playlist.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRemote(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .app.Message.Type type = 1 [default = LIBRARY];
      public boolean hasType() {
        return result.hasType();
      }
      public com.jammed.app.ProtocolMessage.Message.Type getType() {
        return result.getType();
      }
      public Builder setType(com.jammed.app.ProtocolMessage.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.jammed.app.ProtocolMessage.Message.Type.LIBRARY;
        return this;
      }
      
      // repeated .app.Playlist local = 2;
      public java.util.List<com.jammed.app.Protos.Playlist> getLocalList() {
        return java.util.Collections.unmodifiableList(result.local_);
      }
      public int getLocalCount() {
        return result.getLocalCount();
      }
      public com.jammed.app.Protos.Playlist getLocal(int index) {
        return result.getLocal(index);
      }
      public Builder setLocal(int index, com.jammed.app.Protos.Playlist value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.local_.set(index, value);
        return this;
      }
      public Builder setLocal(int index, com.jammed.app.Protos.Playlist.Builder builderForValue) {
        result.local_.set(index, builderForValue.build());
        return this;
      }
      public Builder addLocal(com.jammed.app.Protos.Playlist value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.local_.isEmpty()) {
          result.local_ = new java.util.ArrayList<com.jammed.app.Protos.Playlist>();
        }
        result.local_.add(value);
        return this;
      }
      public Builder addLocal(com.jammed.app.Protos.Playlist.Builder builderForValue) {
        if (result.local_.isEmpty()) {
          result.local_ = new java.util.ArrayList<com.jammed.app.Protos.Playlist>();
        }
        result.local_.add(builderForValue.build());
        return this;
      }
      public Builder addAllLocal(
          java.lang.Iterable<? extends com.jammed.app.Protos.Playlist> values) {
        if (result.local_.isEmpty()) {
          result.local_ = new java.util.ArrayList<com.jammed.app.Protos.Playlist>();
        }
        super.addAll(values, result.local_);
        return this;
      }
      public Builder clearLocal() {
        result.local_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .app.Playlist remote = 3;
      public java.util.List<com.jammed.app.Protos.Playlist> getRemoteList() {
        return java.util.Collections.unmodifiableList(result.remote_);
      }
      public int getRemoteCount() {
        return result.getRemoteCount();
      }
      public com.jammed.app.Protos.Playlist getRemote(int index) {
        return result.getRemote(index);
      }
      public Builder setRemote(int index, com.jammed.app.Protos.Playlist value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.remote_.set(index, value);
        return this;
      }
      public Builder setRemote(int index, com.jammed.app.Protos.Playlist.Builder builderForValue) {
        result.remote_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRemote(com.jammed.app.Protos.Playlist value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.remote_.isEmpty()) {
          result.remote_ = new java.util.ArrayList<com.jammed.app.Protos.Playlist>();
        }
        result.remote_.add(value);
        return this;
      }
      public Builder addRemote(com.jammed.app.Protos.Playlist.Builder builderForValue) {
        if (result.remote_.isEmpty()) {
          result.remote_ = new java.util.ArrayList<com.jammed.app.Protos.Playlist>();
        }
        result.remote_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRemote(
          java.lang.Iterable<? extends com.jammed.app.Protos.Playlist> values) {
        if (result.remote_.isEmpty()) {
          result.remote_ = new java.util.ArrayList<com.jammed.app.Protos.Playlist>();
        }
        super.addAll(values, result.remote_);
        return this;
      }
      public Builder clearRemote() {
        result.remote_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:app.Library)
    }
    
    static {
      defaultInstance = new Library(true);
      com.jammed.app.Protos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:app.Library)
  }
  
  public static final class Search extends
      com.google.protobuf.GeneratedMessage {
    // Use Search.newBuilder() to construct.
    private Search() {
      initFields();
    }
    private Search(boolean noInit) {}
    
    private static final Search defaultInstance;
    public static Search getDefaultInstance() {
      return defaultInstance;
    }
    
    public Search getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jammed.app.Protos.internal_static_app_Search_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jammed.app.Protos.internal_static_app_Search_fieldAccessorTable;
    }
    
    // required .app.Message.Type type = 1 [default = SEARCH];
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private com.jammed.app.ProtocolMessage.Message.Type type_;
    public boolean hasType() { return hasType; }
    public com.jammed.app.ProtocolMessage.Message.Type getType() { return type_; }
    
    // required int32 request = 2;
    public static final int REQUEST_FIELD_NUMBER = 2;
    private boolean hasRequest;
    private int request_ = 0;
    public boolean hasRequest() { return hasRequest; }
    public int getRequest() { return request_; }
    
    // required string query = 3;
    public static final int QUERY_FIELD_NUMBER = 3;
    private boolean hasQuery;
    private java.lang.String query_ = "";
    public boolean hasQuery() { return hasQuery; }
    public java.lang.String getQuery() { return query_; }
    
    private void initFields() {
      type_ = com.jammed.app.ProtocolMessage.Message.Type.SEARCH;
    }
    public final boolean isInitialized() {
      if (!hasType) return false;
      if (!hasRequest) return false;
      if (!hasQuery) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      if (hasRequest()) {
        output.writeInt32(2, getRequest());
      }
      if (hasQuery()) {
        output.writeString(3, getQuery());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      if (hasRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getRequest());
      }
      if (hasQuery()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getQuery());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.jammed.app.Protos.Search parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jammed.app.Protos.Search parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Search parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jammed.app.Protos.Search parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Search parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jammed.app.Protos.Search parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jammed.app.Protos.Search parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jammed.app.Protos.Search parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jammed.app.Protos.Search parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jammed.app.Protos.Search parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jammed.app.Protos.Search prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.jammed.app.Protos.Search result;
      
      // Construct using com.jammed.app.Protos.Search.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.jammed.app.Protos.Search();
        return builder;
      }
      
      protected com.jammed.app.Protos.Search internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.jammed.app.Protos.Search();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jammed.app.Protos.Search.getDescriptor();
      }
      
      public com.jammed.app.Protos.Search getDefaultInstanceForType() {
        return com.jammed.app.Protos.Search.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.jammed.app.Protos.Search build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.jammed.app.Protos.Search buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.jammed.app.Protos.Search buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.jammed.app.Protos.Search returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jammed.app.Protos.Search) {
          return mergeFrom((com.jammed.app.Protos.Search)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.jammed.app.Protos.Search other) {
        if (other == com.jammed.app.Protos.Search.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        if (other.hasQuery()) {
          setQuery(other.getQuery());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.jammed.app.ProtocolMessage.Message.Type value = com.jammed.app.ProtocolMessage.Message.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 16: {
              setRequest(input.readInt32());
              break;
            }
            case 26: {
              setQuery(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .app.Message.Type type = 1 [default = SEARCH];
      public boolean hasType() {
        return result.hasType();
      }
      public com.jammed.app.ProtocolMessage.Message.Type getType() {
        return result.getType();
      }
      public Builder setType(com.jammed.app.ProtocolMessage.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.jammed.app.ProtocolMessage.Message.Type.SEARCH;
        return this;
      }
      
      // required int32 request = 2;
      public boolean hasRequest() {
        return result.hasRequest();
      }
      public int getRequest() {
        return result.getRequest();
      }
      public Builder setRequest(int value) {
        result.hasRequest = true;
        result.request_ = value;
        return this;
      }
      public Builder clearRequest() {
        result.hasRequest = false;
        result.request_ = 0;
        return this;
      }
      
      // required string query = 3;
      public boolean hasQuery() {
        return result.hasQuery();
      }
      public java.lang.String getQuery() {
        return result.getQuery();
      }
      public Builder setQuery(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasQuery = true;
        result.query_ = value;
        return this;
      }
      public Builder clearQuery() {
        result.hasQuery = false;
        result.query_ = getDefaultInstance().getQuery();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:app.Search)
    }
    
    static {
      defaultInstance = new Search(true);
      com.jammed.app.Protos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:app.Search)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_app_Media_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_app_Media_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_app_Playlist_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_app_Playlist_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_app_Library_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_app_Library_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_app_Search_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_app_Search_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013media.proto\022\003app\032\rmessage.proto\"\215\001\n\005Me" +
      "dia\022&\n\004type\030\001 \002(\0162\021.app.Message.Type:\005ME" +
      "DIA\022\020\n\010location\030\002 \002(\t\022\r\n\005title\030\003 \002(\t\022\016\n\006" +
      "length\030\004 \001(\005\022\014\n\004name\030\005 \001(\t\022\016\n\006artist\030\006 \001" +
      "(\t\022\r\n\005album\030\007 \001(\t\"o\n\010Playlist\022)\n\004type\030\001 " +
      "\002(\0162\021.app.Message.Type:\010PLAYLIST\022\031\n\005medi" +
      "a\030\002 \003(\0132\n.app.Media\022\014\n\004host\030\003 \002(\t\022\017\n\007req" +
      "uest\030\004 \001(\005\"p\n\007Library\022(\n\004type\030\001 \002(\0162\021.ap" +
      "p.Message.Type:\007LIBRARY\022\034\n\005local\030\002 \003(\0132\r" +
      ".app.Playlist\022\035\n\006remote\030\003 \003(\0132\r.app.Play",
      "list\"Q\n\006Search\022\'\n\004type\030\001 \002(\0162\021.app.Messa" +
      "ge.Type:\006SEARCH\022\017\n\007request\030\002 \002(\005\022\r\n\005quer" +
      "y\030\003 \002(\tB\030\n\016com.jammed.appB\006Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_app_Media_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_app_Media_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_app_Media_descriptor,
              new java.lang.String[] { "Type", "Location", "Title", "Length", "Name", "Artist", "Album", },
              com.jammed.app.Protos.Media.class,
              com.jammed.app.Protos.Media.Builder.class);
          internal_static_app_Playlist_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_app_Playlist_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_app_Playlist_descriptor,
              new java.lang.String[] { "Type", "Media", "Host", "Request", },
              com.jammed.app.Protos.Playlist.class,
              com.jammed.app.Protos.Playlist.Builder.class);
          internal_static_app_Library_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_app_Library_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_app_Library_descriptor,
              new java.lang.String[] { "Type", "Local", "Remote", },
              com.jammed.app.Protos.Library.class,
              com.jammed.app.Protos.Library.Builder.class);
          internal_static_app_Search_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_app_Search_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_app_Search_descriptor,
              new java.lang.String[] { "Type", "Request", "Query", },
              com.jammed.app.Protos.Search.class,
              com.jammed.app.Protos.Search.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jammed.app.ProtocolMessage.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
